// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA92ddc6eDecodeGithubComKubewardenK8sObjectsApiNetworkingV1alpha1(in *jlexer.Lexer, out *ParentReference) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "group":
			out.Group = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "namespace":
			out.Namespace = string(in.String())
		case "resource":
			out.Resource = string(in.String())
		case "uid":
			out.UID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA92ddc6eEncodeGithubComKubewardenK8sObjectsApiNetworkingV1alpha1(out *jwriter.Writer, in ParentReference) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Group != "" {
		const prefix string = ",\"group\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Group))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Namespace != "" {
		const prefix string = ",\"namespace\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Namespace))
	}
	if in.Resource != "" {
		const prefix string = ",\"resource\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Resource))
	}
	if in.UID != "" {
		const prefix string = ",\"uid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ParentReference) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA92ddc6eEncodeGithubComKubewardenK8sObjectsApiNetworkingV1alpha1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ParentReference) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA92ddc6eEncodeGithubComKubewardenK8sObjectsApiNetworkingV1alpha1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ParentReference) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA92ddc6eDecodeGithubComKubewardenK8sObjectsApiNetworkingV1alpha1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ParentReference) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA92ddc6eDecodeGithubComKubewardenK8sObjectsApiNetworkingV1alpha1(l, v)
}
