// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// EndpointPort EndpointPort is a tuple that describes a single port.
//
// swagger:model EndpointPort
type EndpointPort struct {

	// The name of this port.  This must match the 'name' field in the corresponding ServicePort. Must be a DNS_LABEL. Optional only if one port is defined.
	Name string `json:"name,omitempty"`

	// The port number of the endpoint.
	// Required: true
	Port *int32 `json:"port"`

	// The IP protocol for this port. Must be UDP, TCP, or SCTP. Default is TCP.
	Protocol string `json:"protocol,omitempty"`
}
