// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PodDNSConfigOption PodDNSConfigOption defines DNS resolver options of a pod.
//
// swagger:model PodDNSConfigOption
type PodDNSConfigOption struct {

	// Name is this DNS resolver option's name. Required.
	Name string `json:"name,omitempty"`

	// Value is this DNS resolver option's value.
	Value string `json:"value,omitempty"`
}
