// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ResourceStatus resource status
//
// swagger:model ResourceStatus
type ResourceStatus struct {

	// Name of the resource. Must be unique within the pod and match one of the resources from the pod spec.
	// Required: true
	Name *string `json:"name"`

	// List of unique Resources health. Each element in the list contains an unique resource ID and resource health. At a minimum, ResourceID must uniquely identify the Resource allocated to the Pod on the Node for the lifetime of a Pod. See ResourceID type for it's definition.
	Resources []*ResourceHealth `json:"resources,omitempty"`
}
