// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDadf7631DecodeGithubComKubewardenK8sObjectsApiAuditregistrationV1alpha1(in *jlexer.Lexer, out *WebhookThrottleConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "burst":
			out.Burst = int64(in.Int64())
		case "qps":
			out.QPS = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDadf7631EncodeGithubComKubewardenK8sObjectsApiAuditregistrationV1alpha1(out *jwriter.Writer, in WebhookThrottleConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Burst != 0 {
		const prefix string = ",\"burst\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.Burst))
	}
	if in.QPS != 0 {
		const prefix string = ",\"qps\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.QPS))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WebhookThrottleConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDadf7631EncodeGithubComKubewardenK8sObjectsApiAuditregistrationV1alpha1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WebhookThrottleConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDadf7631EncodeGithubComKubewardenK8sObjectsApiAuditregistrationV1alpha1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WebhookThrottleConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDadf7631DecodeGithubComKubewardenK8sObjectsApiAuditregistrationV1alpha1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WebhookThrottleConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDadf7631DecodeGithubComKubewardenK8sObjectsApiAuditregistrationV1alpha1(l, v)
}
