// Code generated by go-swagger; DO NOT EDIT.

package v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// BasicDevice BasicDevice defines one device instance.
//
// swagger:model BasicDevice
type BasicDevice struct {

	// Attributes defines the set of attributes for this device. The name of each attribute must be unique in that set.
	//
	// The maximum number of attributes and capacities combined is 32.
	Attributes map[string]*DeviceAttribute `json:"attributes,omitempty"`

	// Capacity defines the set of capacities for this device. The name of each capacity must be unique in that set.
	//
	// The maximum number of attributes and capacities combined is 32.
	Capacity map[string]*DeviceCapacity `json:"capacity,omitempty"`
}
