// Code generated by go-swagger; DO NOT EDIT.

package v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CounterSet CounterSet defines a named set of counters that are available to be used by devices defined in the ResourceSlice.
//
// The counters are not allocatable by themselves, but can be referenced by devices. When a device is allocated, the portion of counters it uses will no longer be available for use by other devices.
//
// swagger:model CounterSet
type CounterSet struct {

	// Counters defines the set of counters for this CounterSet The name of each counter must be unique in that set and must be a DNS label.
	//
	// The maximum number of counters is 32.
	// Required: true
	Counters map[string]Counter `json:"counters"`

	// Name defines the name of the counter set. It must be a DNS label.
	// Required: true
	Name *string `json:"name"`
}
