// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD40f6b73DecodeGithubComKubewardenK8sObjectsApiPolicyV1beta1(in *jlexer.Lexer, out *AllowedCSIDriver) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD40f6b73EncodeGithubComKubewardenK8sObjectsApiPolicyV1beta1(out *jwriter.Writer, in AllowedCSIDriver) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AllowedCSIDriver) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD40f6b73EncodeGithubComKubewardenK8sObjectsApiPolicyV1beta1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AllowedCSIDriver) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD40f6b73EncodeGithubComKubewardenK8sObjectsApiPolicyV1beta1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AllowedCSIDriver) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD40f6b73DecodeGithubComKubewardenK8sObjectsApiPolicyV1beta1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AllowedCSIDriver) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD40f6b73DecodeGithubComKubewardenK8sObjectsApiPolicyV1beta1(l, v)
}
