// Code generated by go-swagger; DO NOT EDIT.

package v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// HostPortRange HostPortRange defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined.
//
// swagger:model HostPortRange
type HostPortRange struct {

	// max is the end of the range, inclusive.
	// Required: true
	Max *int32 `json:"max"`

	// min is the start of the range, inclusive.
	// Required: true
	Min *int32 `json:"min"`
}
