// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ForNode ForNode provides information about which nodes should consume this endpoint.
//
// swagger:model ForNode
type ForNode struct {

	// name represents the name of the node.
	// Required: true
	Name *string `json:"name"`
}
