// Code generated by go-swagger; DO NOT EDIT.

package v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	apimachinery_pkg_api_resource "github.com/kubewarden/k8s-objects/apimachinery/pkg/api/resource"
)

// MetricValueStatus MetricValueStatus holds the current value for a metric
//
// swagger:model MetricValueStatus
type MetricValueStatus struct {

	// currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.
	AverageUtilization int32 `json:"averageUtilization,omitempty"`

	// averageValue is the current value of the average of the metric across all relevant pods (as a quantity)
	AverageValue apimachinery_pkg_api_resource.Quantity `json:"averageValue,omitempty"`

	// value is the current value of the metric (as a quantity).
	Value apimachinery_pkg_api_resource.Quantity `json:"value,omitempty"`
}
