// Code generated by go-swagger; DO NOT EDIT.

package v2beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	apimachinery_pkg_api_resource "github.com/kubewarden/k8s-objects/apimachinery/pkg/api/resource"
)

// ContainerResourceMetricStatus ContainerResourceMetricStatus indicates the current value of a resource metric known to Kubernetes, as specified in requests and limits, describing a single container in each pod in the current scale target (e.g. CPU or memory).  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the "pods" source.
//
// swagger:model ContainerResourceMetricStatus
type ContainerResourceMetricStatus struct {

	// container is the name of the container in the pods of the scaling target
	// Required: true
	Container *string `json:"container"`

	// currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.  It will only be present if `targetAverageValue` was set in the corresponding metric specification.
	CurrentAverageUtilization int32 `json:"currentAverageUtilization,omitempty"`

	// currentAverageValue is the current value of the average of the resource metric across all relevant pods, as a raw value (instead of as a percentage of the request), similar to the "pods" metric source type. It will always be set, regardless of the corresponding metric specification.
	// Required: true
	CurrentAverageValue *apimachinery_pkg_api_resource.Quantity `json:"currentAverageValue"`

	// name is the name of the resource in question.
	// Required: true
	Name *string `json:"name"`
}
