// Code generated by go-swagger; DO NOT EDIT.

package v1alpha2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	jsonext "encoding/json"
)

// ResourceRequest ResourceRequest is a request for resources from one particular driver.
//
// swagger:model ResourceRequest
type ResourceRequest struct {

	// NamedResources describes a request for resources with the named resources model.
	NamedResources *NamedResourcesRequest `json:"namedResources,omitempty"`

	// VendorParameters are arbitrary setup parameters for the requested resource. They are ignored while allocating a claim.
	VendorParameters jsonext.RawMessage `json:"vendorParameters,omitempty"`
}
