// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha2

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2ad56fc3DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(in *jlexer.Lexer, out *ResourceHandle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			out.Data = string(in.String())
		case "driverName":
			out.DriverName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ad56fc3EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(out *jwriter.Writer, in ResourceHandle) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Data != "" {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Data))
	}
	if in.DriverName != "" {
		const prefix string = ",\"driverName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DriverName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResourceHandle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ad56fc3EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResourceHandle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ad56fc3EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResourceHandle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ad56fc3DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResourceHandle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ad56fc3DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(l, v)
}
