// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha2

import (
	json "encoding/json"
	_v11 "github.com/kubewarden/k8s-objects/api/core/v1"
	_v1 "github.com/kubewarden/k8s-objects/apimachinery/pkg/apis/meta/v1"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson19697525DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(in *jlexer.Lexer, out *ResourceClass) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "apiVersion":
			out.APIVersion = string(in.String())
		case "driverName":
			if in.IsNull() {
				in.Skip()
				out.DriverName = nil
			} else {
				if out.DriverName == nil {
					out.DriverName = new(string)
				}
				*out.DriverName = string(in.String())
			}
		case "kind":
			out.Kind = string(in.String())
		case "metadata":
			if in.IsNull() {
				in.Skip()
				out.Metadata = nil
			} else {
				if out.Metadata == nil {
					out.Metadata = new(_v1.ObjectMeta)
				}
				(*out.Metadata).UnmarshalEasyJSON(in)
			}
		case "parametersRef":
			if in.IsNull() {
				in.Skip()
				out.ParametersRef = nil
			} else {
				if out.ParametersRef == nil {
					out.ParametersRef = new(ResourceClassParametersReference)
				}
				easyjson19697525DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha21(in, out.ParametersRef)
			}
		case "suitableNodes":
			if in.IsNull() {
				in.Skip()
				out.SuitableNodes = nil
			} else {
				if out.SuitableNodes == nil {
					out.SuitableNodes = new(_v11.NodeSelector)
				}
				(*out.SuitableNodes).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19697525EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(out *jwriter.Writer, in ResourceClass) {
	out.RawByte('{')
	first := true
	_ = first
	if in.APIVersion != "" {
		const prefix string = ",\"apiVersion\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.APIVersion))
	}
	{
		const prefix string = ",\"driverName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.DriverName == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DriverName))
		}
	}
	if in.Kind != "" {
		const prefix string = ",\"kind\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	if in.Metadata != nil {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		(*in.Metadata).MarshalEasyJSON(out)
	}
	if in.ParametersRef != nil {
		const prefix string = ",\"parametersRef\":"
		out.RawString(prefix)
		easyjson19697525EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha21(out, *in.ParametersRef)
	}
	if in.SuitableNodes != nil {
		const prefix string = ",\"suitableNodes\":"
		out.RawString(prefix)
		(*in.SuitableNodes).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResourceClass) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson19697525EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResourceClass) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson19697525EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResourceClass) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson19697525DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResourceClass) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson19697525DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(l, v)
}
func easyjson19697525DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha21(in *jlexer.Lexer, out *ResourceClassParametersReference) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "apiGroup":
			out.APIGroup = string(in.String())
		case "kind":
			if in.IsNull() {
				in.Skip()
				out.Kind = nil
			} else {
				if out.Kind == nil {
					out.Kind = new(string)
				}
				*out.Kind = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "namespace":
			out.Namespace = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19697525EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha21(out *jwriter.Writer, in ResourceClassParametersReference) {
	out.RawByte('{')
	first := true
	_ = first
	if in.APIGroup != "" {
		const prefix string = ",\"apiGroup\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.APIGroup))
	}
	{
		const prefix string = ",\"kind\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Kind == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Kind))
		}
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	if in.Namespace != "" {
		const prefix string = ",\"namespace\":"
		out.RawString(prefix)
		out.String(string(in.Namespace))
	}
	out.RawByte('}')
}
