// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha2

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE5546390DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(in *jlexer.Lexer, out *ResourceClaimStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "allocation":
			if in.IsNull() {
				in.Skip()
				out.Allocation = nil
			} else {
				if out.Allocation == nil {
					out.Allocation = new(AllocationResult)
				}
				(*out.Allocation).UnmarshalEasyJSON(in)
			}
		case "deallocationRequested":
			out.DeallocationRequested = bool(in.Bool())
		case "driverName":
			out.DriverName = string(in.String())
		case "reservedFor":
			if in.IsNull() {
				in.Skip()
				out.ReservedFor = nil
			} else {
				in.Delim('[')
				if out.ReservedFor == nil {
					if !in.IsDelim(']') {
						out.ReservedFor = make([]*ResourceClaimConsumerReference, 0, 8)
					} else {
						out.ReservedFor = []*ResourceClaimConsumerReference{}
					}
				} else {
					out.ReservedFor = (out.ReservedFor)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *ResourceClaimConsumerReference
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(ResourceClaimConsumerReference)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.ReservedFor = append(out.ReservedFor, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE5546390EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(out *jwriter.Writer, in ResourceClaimStatus) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Allocation != nil {
		const prefix string = ",\"allocation\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Allocation).MarshalEasyJSON(out)
	}
	if in.DeallocationRequested {
		const prefix string = ",\"deallocationRequested\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.DeallocationRequested))
	}
	if in.DriverName != "" {
		const prefix string = ",\"driverName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DriverName))
	}
	if len(in.ReservedFor) != 0 {
		const prefix string = ",\"reservedFor\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.ReservedFor {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResourceClaimStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE5546390EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResourceClaimStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE5546390EncodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResourceClaimStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE5546390DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResourceClaimStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE5546390DecodeGithubComKubewardenK8sObjectsApiResourceV1alpha2(l, v)
}
