// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE0e85fe5DecodeGithubComKubewardenK8sObjectsApiStorageV1(in *jlexer.Lexer, out *VolumeNodeResources) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "count":
			out.Count = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0e85fe5EncodeGithubComKubewardenK8sObjectsApiStorageV1(out *jwriter.Writer, in VolumeNodeResources) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Count != 0 {
		const prefix string = ",\"count\":"
		first = false
		out.RawString(prefix[1:])
		out.Int32(int32(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VolumeNodeResources) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0e85fe5EncodeGithubComKubewardenK8sObjectsApiStorageV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VolumeNodeResources) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0e85fe5EncodeGithubComKubewardenK8sObjectsApiStorageV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VolumeNodeResources) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0e85fe5DecodeGithubComKubewardenK8sObjectsApiStorageV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VolumeNodeResources) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0e85fe5DecodeGithubComKubewardenK8sObjectsApiStorageV1(l, v)
}
