// Code generated by go-swagger; DO NOT EDIT.

package v1beta2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	api_core_v1 "github.com/kubewarden/k8s-objects/api/core/v1"
)

// Device Device represents one individual hardware instance that can be selected based on its attributes. Besides the name, exactly one field must be set.
//
// swagger:model Device
type Device struct {

	// AllNodes indicates that all nodes have access to the device.
	//
	// Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
	AllNodes bool `json:"allNodes,omitempty"`

	// Attributes defines the set of attributes for this device. The name of each attribute must be unique in that set.
	//
	// The maximum number of attributes and capacities combined is 32.
	Attributes map[string]*DeviceAttribute `json:"attributes,omitempty"`

	// Capacity defines the set of capacities for this device. The name of each capacity must be unique in that set.
	//
	// The maximum number of attributes and capacities combined is 32.
	Capacity map[string]*DeviceCapacity `json:"capacity,omitempty"`

	// ConsumesCounters defines a list of references to sharedCounters and the set of counters that the device will consume from those counter sets.
	//
	// There can only be a single entry per counterSet.
	//
	// The total number of device counter consumption entries must be <= 32. In addition, the total number in the entire ResourceSlice must be <= 1024 (for example, 64 devices with 16 counters each).
	ConsumesCounters []*DeviceCounterConsumption `json:"consumesCounters,omitempty"`

	// Name is unique identifier among all devices managed by the driver in the pool. It must be a DNS label.
	// Required: true
	Name *string `json:"name"`

	// NodeName identifies the node where the device is available.
	//
	// Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
	NodeName string `json:"nodeName,omitempty"`

	// NodeSelector defines the nodes where the device is available.
	//
	// Must use exactly one term.
	//
	// Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
	NodeSelector *api_core_v1.NodeSelector `json:"nodeSelector,omitempty"`

	// If specified, these are the driver-defined taints.
	//
	// The maximum number of taints is 4.
	//
	// This is an alpha field and requires enabling the DRADeviceTaints feature gate.
	Taints []*DeviceTaint `json:"taints,omitempty"`
}
