// Code generated by go-swagger; DO NOT EDIT.

package v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GroupVersionResource The names of the group, the version, and the resource.
//
// swagger:model GroupVersionResource
type GroupVersionResource struct {

	// The name of the group.
	Group string `json:"group,omitempty"`

	// The name of the resource.
	Resource string `json:"resource,omitempty"`

	// The name of the version.
	Version string `json:"version,omitempty"`
}
