// Code generated by go-swagger; DO NOT EDIT.

package v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// StorageVersionMigrationStatus Status of the storage version migration.
//
// swagger:model StorageVersionMigrationStatus
type StorageVersionMigrationStatus struct {

	// The latest available observations of the migration's current state.
	Conditions []*MigrationCondition `json:"conditions,omitempty"`

	// ResourceVersion to compare with the GC cache for performing the migration. This is the current resource version of given group, version and resource when kube-controller-manager first observes this StorageVersionMigration resource.
	ResourceVersion string `json:"resourceVersion,omitempty"`
}
