// Code generated by go-swagger; DO NOT EDIT.

package v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// StorageVersionMigrationSpec Spec of the storage version migration.
//
// swagger:model StorageVersionMigrationSpec
type StorageVersionMigrationSpec struct {

	// The token used in the list options to get the next chunk of objects to migrate. When the .status.conditions indicates the migration is "Running", users can use this token to check the progress of the migration.
	ContinueToken string `json:"continueToken,omitempty"`

	// The resource that is being migrated. The migrator sends requests to the endpoint serving the resource. Immutable.
	// Required: true
	Resource *GroupVersionResource `json:"resource"`
}
