// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7a56214aDecodeGithubComKubewardenK8sObjectsApiResourceV1alpha1(in *jlexer.Lexer, out *PodSchedulingSpec) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "potentialNodes":
			if in.IsNull() {
				in.Skip()
				out.PotentialNodes = nil
			} else {
				in.Delim('[')
				if out.PotentialNodes == nil {
					if !in.IsDelim(']') {
						out.PotentialNodes = make([]string, 0, 4)
					} else {
						out.PotentialNodes = []string{}
					}
				} else {
					out.PotentialNodes = (out.PotentialNodes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.PotentialNodes = append(out.PotentialNodes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "selectedNode":
			out.SelectedNode = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7a56214aEncodeGithubComKubewardenK8sObjectsApiResourceV1alpha1(out *jwriter.Writer, in PodSchedulingSpec) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.PotentialNodes) != 0 {
		const prefix string = ",\"potentialNodes\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.PotentialNodes {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	if in.SelectedNode != "" {
		const prefix string = ",\"selectedNode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SelectedNode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PodSchedulingSpec) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7a56214aEncodeGithubComKubewardenK8sObjectsApiResourceV1alpha1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PodSchedulingSpec) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7a56214aEncodeGithubComKubewardenK8sObjectsApiResourceV1alpha1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PodSchedulingSpec) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7a56214aDecodeGithubComKubewardenK8sObjectsApiResourceV1alpha1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PodSchedulingSpec) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7a56214aDecodeGithubComKubewardenK8sObjectsApiResourceV1alpha1(l, v)
}
