// Code generated by go-swagger; DO NOT EDIT.

package v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// NonResourceRule NonResourceRule holds information that describes a rule for the non-resource
//
// swagger:model NonResourceRule
type NonResourceRule struct {

	// NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path.  "*" means all.
	NonResourceURLs []string `json:"nonResourceURLs,omitempty"`

	// Verb is a list of kubernetes non-resource API verbs, like: get, post, put, delete, patch, head, options.  "*" means all.
	// Required: true
	Verbs []string `json:"verbs"`
}
