// Code generated by go-swagger; DO NOT EDIT.

package v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/mailru/easyjson"
)

// JSONSchemaProps JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).
//
// swagger:model JSONSchemaProps
type JSONSchemaProps struct {

	// dollar ref
	DollarRef string `json:"$ref,omitempty"`

	// dollar schema
	DollarSchema string `json:"$schema,omitempty"`

	// additional items
	AdditionalItems easyjson.RawMessage `json:"additionalItems,omitempty"`

	// additional properties
	AdditionalProperties easyjson.RawMessage `json:"additionalProperties,omitempty"`

	// all of
	AllOf []*JSONSchemaProps `json:"allOf,omitempty"`

	// any of
	AnyOf []*JSONSchemaProps `json:"anyOf,omitempty"`

	// default
	Default easyjson.RawMessage `json:"default,omitempty"`

	// definitions
	Definitions map[string]*JSONSchemaProps `json:"definitions,omitempty"`

	// dependencies
	Dependencies map[string]easyjson.RawMessage `json:"dependencies,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// enum
	Enum []easyjson.RawMessage `json:"enum,omitempty"`

	// example
	Example easyjson.RawMessage `json:"example,omitempty"`

	// exclusive maximum
	ExclusiveMaximum bool `json:"exclusiveMaximum,omitempty"`

	// exclusive minimum
	ExclusiveMinimum bool `json:"exclusiveMinimum,omitempty"`

	// external docs
	ExternalDocs *ExternalDocumentation `json:"externalDocs,omitempty"`

	// format
	Format string `json:"format,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// items
	Items easyjson.RawMessage `json:"items,omitempty"`

	// max items
	MaxItems int64 `json:"maxItems,omitempty"`

	// max length
	MaxLength int64 `json:"maxLength,omitempty"`

	// max properties
	MaxProperties int64 `json:"maxProperties,omitempty"`

	// maximum
	Maximum float64 `json:"maximum,omitempty"`

	// min items
	MinItems int64 `json:"minItems,omitempty"`

	// min length
	MinLength int64 `json:"minLength,omitempty"`

	// min properties
	MinProperties int64 `json:"minProperties,omitempty"`

	// minimum
	Minimum float64 `json:"minimum,omitempty"`

	// multiple of
	MultipleOf float64 `json:"multipleOf,omitempty"`

	// not
	Not *JSONSchemaProps `json:"not,omitempty"`

	// nullable
	Nullable bool `json:"nullable,omitempty"`

	// one of
	OneOf []*JSONSchemaProps `json:"oneOf,omitempty"`

	// pattern
	Pattern string `json:"pattern,omitempty"`

	// pattern properties
	PatternProperties map[string]*JSONSchemaProps `json:"patternProperties,omitempty"`

	// properties
	Properties map[string]*JSONSchemaProps `json:"properties,omitempty"`

	// required
	Required []string `json:"required,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// unique items
	UniqueItems bool `json:"uniqueItems,omitempty"`
}
