// Code generated by go-swagger; DO NOT EDIT.

package v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ServiceReference ServiceReference holds a reference to Service.legacy.k8s.io
//
// swagger:model ServiceReference
type ServiceReference struct {

	// name is the name of the service. Required
	// Required: true
	Name *string `json:"name"`

	// namespace is the namespace of the service. Required
	// Required: true
	Namespace *string `json:"namespace"`

	// path is an optional URL path at which the webhook will be contacted.
	Path string `json:"path,omitempty"`

	// port is an optional service port at which the webhook will be contacted. `port` should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility.
	Port int32 `json:"port,omitempty"`
}
