// Code generated by go-swagger; DO NOT EDIT.

package v1alpha3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ResourceClaimSpec ResourceClaimSpec defines what is being requested in a ResourceClaim and how to configure it.
//
// swagger:model ResourceClaimSpec
type ResourceClaimSpec struct {

	// Devices defines how to request devices.
	Devices *DeviceClaim `json:"devices,omitempty"`
}
