// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF7aeaa87DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(in *jlexer.Lexer, out *ExpressionWarning) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fieldRef":
			if in.IsNull() {
				in.Skip()
				out.FieldRef = nil
			} else {
				if out.FieldRef == nil {
					out.FieldRef = new(string)
				}
				*out.FieldRef = string(in.String())
			}
		case "warning":
			if in.IsNull() {
				in.Skip()
				out.Warning = nil
			} else {
				if out.Warning == nil {
					out.Warning = new(string)
				}
				*out.Warning = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF7aeaa87EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(out *jwriter.Writer, in ExpressionWarning) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fieldRef\":"
		out.RawString(prefix[1:])
		if in.FieldRef == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.FieldRef))
		}
	}
	{
		const prefix string = ",\"warning\":"
		out.RawString(prefix)
		if in.Warning == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Warning))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExpressionWarning) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF7aeaa87EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExpressionWarning) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF7aeaa87EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExpressionWarning) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF7aeaa87DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExpressionWarning) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF7aeaa87DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(l, v)
}
