// Code generated by go-swagger; DO NOT EDIT.

package v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Mutation Mutation specifies the CEL expression which is used to apply the Mutation.
//
// swagger:model Mutation
type Mutation struct {

	// applyConfiguration defines the desired configuration values of an object. The configuration is applied to the admission object using [structured merge diff](https://github.com/kubernetes-sigs/structured-merge-diff). A CEL expression is used to create apply configuration.
	ApplyConfiguration *ApplyConfiguration `json:"applyConfiguration,omitempty"`

	// jsonPatch defines a [JSON patch](https://jsonpatch.com/) operation to perform a mutation to the object. A CEL expression is used to create the JSON patch.
	JSONPatch *JSONPatch `json:"jsonPatch,omitempty"`

	// patchType indicates the patch strategy used. Allowed values are "ApplyConfiguration" and "JSONPatch". Required.
	// Required: true
	PatchType *string `json:"patchType"`
}
