// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	_v1 "github.com/kubewarden/k8s-objects/apimachinery/pkg/apis/meta/v1"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson98af83a7DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(in *jlexer.Lexer, out *ValidatingAdmissionPolicyStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "conditions":
			if in.IsNull() {
				in.Skip()
				out.Conditions = nil
			} else {
				in.Delim('[')
				if out.Conditions == nil {
					if !in.IsDelim(']') {
						out.Conditions = make([]*_v1.Condition, 0, 8)
					} else {
						out.Conditions = []*_v1.Condition{}
					}
				} else {
					out.Conditions = (out.Conditions)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *_v1.Condition
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(_v1.Condition)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Conditions = append(out.Conditions, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "observedGeneration":
			out.ObservedGeneration = int64(in.Int64())
		case "typeChecking":
			if in.IsNull() {
				in.Skip()
				out.TypeChecking = nil
			} else {
				if out.TypeChecking == nil {
					out.TypeChecking = new(TypeChecking)
				}
				(*out.TypeChecking).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson98af83a7EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(out *jwriter.Writer, in ValidatingAdmissionPolicyStatus) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Conditions) != 0 {
		const prefix string = ",\"conditions\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Conditions {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	if in.ObservedGeneration != 0 {
		const prefix string = ",\"observedGeneration\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.ObservedGeneration))
	}
	if in.TypeChecking != nil {
		const prefix string = ",\"typeChecking\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.TypeChecking).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ValidatingAdmissionPolicyStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson98af83a7EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ValidatingAdmissionPolicyStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson98af83a7EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ValidatingAdmissionPolicyStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson98af83a7DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ValidatingAdmissionPolicyStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson98af83a7DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1alpha1(l, v)
}
