// Code generated by go-swagger; DO NOT EDIT.

package v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	apimachinery_pkg_apis_meta_v1 "github.com/kubewarden/k8s-objects/apimachinery/pkg/apis/meta/v1"
)

// StorageVersionCondition Describes the state of the storageVersion at a certain point.
//
// swagger:model StorageVersionCondition
type StorageVersionCondition struct {

	// Last time the condition transitioned from one status to another.
	LastTransitionTime *apimachinery_pkg_apis_meta_v1.Time `json:"lastTransitionTime,omitempty"`

	// A human readable message indicating details about the transition.
	// Required: true
	Message *string `json:"message"`

	// If set, this represents the .metadata.generation that the condition was set based upon.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// The reason for the condition's last transition.
	// Required: true
	Reason *string `json:"reason"`

	// Status of the condition, one of True, False, Unknown.
	// Required: true
	Status *string `json:"status"`

	// Type of the condition.
	// Required: true
	Type *string `json:"type"`
}
