// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson62d06692DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta1(in *jlexer.Lexer, out *ValidatingWebhookConfiguration) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "apiVersion":
			out.APIVersion = string(in.String())
		case "kind":
			out.Kind = string(in.String())
		case "metadata":
			(out.Metadata).UnmarshalEasyJSON(in)
		case "webhooks":
			if in.IsNull() {
				in.Skip()
				out.Webhooks = nil
			} else {
				in.Delim('[')
				if out.Webhooks == nil {
					if !in.IsDelim(']') {
						out.Webhooks = make([]*Webhook, 0, 8)
					} else {
						out.Webhooks = []*Webhook{}
					}
				} else {
					out.Webhooks = (out.Webhooks)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Webhook
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Webhook)
						}
						easyjson62d06692DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta11(in, v1)
					}
					out.Webhooks = append(out.Webhooks, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson62d06692EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta1(out *jwriter.Writer, in ValidatingWebhookConfiguration) {
	out.RawByte('{')
	first := true
	_ = first
	if in.APIVersion != "" {
		const prefix string = ",\"apiVersion\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.APIVersion))
	}
	if in.Kind != "" {
		const prefix string = ",\"kind\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Kind))
	}
	if true {
		const prefix string = ",\"metadata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Metadata).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"webhooks\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Webhooks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Webhooks {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					easyjson62d06692EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta11(out, *v3)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ValidatingWebhookConfiguration) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson62d06692EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ValidatingWebhookConfiguration) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson62d06692EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ValidatingWebhookConfiguration) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson62d06692DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ValidatingWebhookConfiguration) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson62d06692DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta1(l, v)
}
func easyjson62d06692DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta11(in *jlexer.Lexer, out *Webhook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "admissionReviewVersions":
			if in.IsNull() {
				in.Skip()
				out.AdmissionReviewVersions = nil
			} else {
				in.Delim('[')
				if out.AdmissionReviewVersions == nil {
					if !in.IsDelim(']') {
						out.AdmissionReviewVersions = make([]string, 0, 4)
					} else {
						out.AdmissionReviewVersions = []string{}
					}
				} else {
					out.AdmissionReviewVersions = (out.AdmissionReviewVersions)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.AdmissionReviewVersions = append(out.AdmissionReviewVersions, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "clientConfig":
			if in.IsNull() {
				in.Skip()
				out.ClientConfig = nil
			} else {
				if out.ClientConfig == nil {
					out.ClientConfig = new(WebhookClientConfig)
				}
				easyjson62d06692DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta12(in, out.ClientConfig)
			}
		case "failurePolicy":
			out.FailurePolicy = string(in.String())
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "namespaceSelector":
			(out.NamespaceSelector).UnmarshalEasyJSON(in)
		case "rules":
			if in.IsNull() {
				in.Skip()
				out.Rules = nil
			} else {
				in.Delim('[')
				if out.Rules == nil {
					if !in.IsDelim(']') {
						out.Rules = make([]*RuleWithOperations, 0, 8)
					} else {
						out.Rules = []*RuleWithOperations{}
					}
				} else {
					out.Rules = (out.Rules)[:0]
				}
				for !in.IsDelim(']') {
					var v5 *RuleWithOperations
					if in.IsNull() {
						in.Skip()
						v5 = nil
					} else {
						if v5 == nil {
							v5 = new(RuleWithOperations)
						}
						(*v5).UnmarshalEasyJSON(in)
					}
					out.Rules = append(out.Rules, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "sideEffects":
			out.SideEffects = string(in.String())
		case "timeoutSeconds":
			out.TimeoutSeconds = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson62d06692EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta11(out *jwriter.Writer, in Webhook) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"admissionReviewVersions\":"
		out.RawString(prefix[1:])
		if in.AdmissionReviewVersions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.AdmissionReviewVersions {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"clientConfig\":"
		out.RawString(prefix)
		if in.ClientConfig == nil {
			out.RawString("null")
		} else {
			easyjson62d06692EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta12(out, *in.ClientConfig)
		}
	}
	if in.FailurePolicy != "" {
		const prefix string = ",\"failurePolicy\":"
		out.RawString(prefix)
		out.String(string(in.FailurePolicy))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	if true {
		const prefix string = ",\"namespaceSelector\":"
		out.RawString(prefix)
		(in.NamespaceSelector).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"rules\":"
		out.RawString(prefix)
		if in.Rules == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Rules {
				if v8 > 0 {
					out.RawByte(',')
				}
				if v9 == nil {
					out.RawString("null")
				} else {
					(*v9).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	if in.SideEffects != "" {
		const prefix string = ",\"sideEffects\":"
		out.RawString(prefix)
		out.String(string(in.SideEffects))
	}
	if in.TimeoutSeconds != 0 {
		const prefix string = ",\"timeoutSeconds\":"
		out.RawString(prefix)
		out.Int32(int32(in.TimeoutSeconds))
	}
	out.RawByte('}')
}
func easyjson62d06692DecodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta12(in *jlexer.Lexer, out *WebhookClientConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "caBundle":
			if in.IsNull() {
				in.Skip()
				out.CaBundle = nil
			} else {
				out.CaBundle = in.Bytes()
			}
		case "service":
			if in.IsNull() {
				in.Skip()
				out.Service = nil
			} else {
				if out.Service == nil {
					out.Service = new(ServiceReference)
				}
				(*out.Service).UnmarshalEasyJSON(in)
			}
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson62d06692EncodeGithubComKubewardenK8sObjectsApiAdmissionregistrationV1beta12(out *jwriter.Writer, in WebhookClientConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.CaBundle) != 0 {
		const prefix string = ",\"caBundle\":"
		first = false
		out.RawString(prefix[1:])
		out.Base64Bytes(in.CaBundle)
	}
	if in.Service != nil {
		const prefix string = ",\"service\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Service).MarshalEasyJSON(out)
	}
	if in.URL != "" {
		const prefix string = ",\"url\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.URL))
	}
	out.RawByte('}')
}
