// Code generated by go-swagger; DO NOT EDIT.

package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Info Info contains versioning information. how we'll want to distribute that information.
//
// swagger:model Info
type Info struct {

	// build date
	// Required: true
	BuildDate *string `json:"buildDate"`

	// compiler
	// Required: true
	Compiler *string `json:"compiler"`

	// EmulationMajor is the major version of the emulation version
	EmulationMajor string `json:"emulationMajor,omitempty"`

	// EmulationMinor is the minor version of the emulation version
	EmulationMinor string `json:"emulationMinor,omitempty"`

	// git commit
	// Required: true
	GitCommit *string `json:"gitCommit"`

	// git tree state
	// Required: true
	GitTreeState *string `json:"gitTreeState"`

	// git version
	// Required: true
	GitVersion *string `json:"gitVersion"`

	// go version
	// Required: true
	GoVersion *string `json:"goVersion"`

	// Major is the major version of the binary version
	// Required: true
	Major *string `json:"major"`

	// MinCompatibilityMajor is the major version of the minimum compatibility version
	MinCompatibilityMajor string `json:"minCompatibilityMajor,omitempty"`

	// MinCompatibilityMinor is the minor version of the minimum compatibility version
	MinCompatibilityMinor string `json:"minCompatibilityMinor,omitempty"`

	// Minor is the minor version of the binary version
	// Required: true
	Minor *string `json:"minor"`

	// platform
	// Required: true
	Platform *string `json:"platform"`
}
