// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1

import (
	json "encoding/json"
	_v1 "github.com/kubewarden/k8s-objects/apimachinery/pkg/apis/meta/v1"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA0c3999bDecodeGithubComKubewardenK8sObjectsApiPolicyV1(in *jlexer.Lexer, out *Eviction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "apiVersion":
			out.APIVersion = string(in.String())
		case "deleteOptions":
			if in.IsNull() {
				in.Skip()
				out.DeleteOptions = nil
			} else {
				if out.DeleteOptions == nil {
					out.DeleteOptions = new(_v1.DeleteOptions)
				}
				(*out.DeleteOptions).UnmarshalEasyJSON(in)
			}
		case "kind":
			out.Kind = string(in.String())
		case "metadata":
			if in.IsNull() {
				in.Skip()
				out.Metadata = nil
			} else {
				if out.Metadata == nil {
					out.Metadata = new(_v1.ObjectMeta)
				}
				(*out.Metadata).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA0c3999bEncodeGithubComKubewardenK8sObjectsApiPolicyV1(out *jwriter.Writer, in Eviction) {
	out.RawByte('{')
	first := true
	_ = first
	if in.APIVersion != "" {
		const prefix string = ",\"apiVersion\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.APIVersion))
	}
	if in.DeleteOptions != nil {
		const prefix string = ",\"deleteOptions\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.DeleteOptions).MarshalEasyJSON(out)
	}
	if in.Kind != "" {
		const prefix string = ",\"kind\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Kind))
	}
	if in.Metadata != nil {
		const prefix string = ",\"metadata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Metadata).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Eviction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA0c3999bEncodeGithubComKubewardenK8sObjectsApiPolicyV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Eviction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA0c3999bEncodeGithubComKubewardenK8sObjectsApiPolicyV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Eviction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA0c3999bDecodeGithubComKubewardenK8sObjectsApiPolicyV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Eviction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA0c3999bDecodeGithubComKubewardenK8sObjectsApiPolicyV1(l, v)
}
