// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v2beta2

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD6dedb2cDecodeGithubComKubewardenK8sObjectsApiAutoscalingV2beta2(in *jlexer.Lexer, out *PodsMetricStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "current":
			if in.IsNull() {
				in.Skip()
				out.Current = nil
			} else {
				if out.Current == nil {
					out.Current = new(MetricValueStatus)
				}
				(*out.Current).UnmarshalEasyJSON(in)
			}
		case "metric":
			if in.IsNull() {
				in.Skip()
				out.Metric = nil
			} else {
				if out.Metric == nil {
					out.Metric = new(MetricIdentifier)
				}
				(*out.Metric).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD6dedb2cEncodeGithubComKubewardenK8sObjectsApiAutoscalingV2beta2(out *jwriter.Writer, in PodsMetricStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"current\":"
		out.RawString(prefix[1:])
		if in.Current == nil {
			out.RawString("null")
		} else {
			(*in.Current).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"metric\":"
		out.RawString(prefix)
		if in.Metric == nil {
			out.RawString("null")
		} else {
			(*in.Metric).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PodsMetricStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD6dedb2cEncodeGithubComKubewardenK8sObjectsApiAutoscalingV2beta2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PodsMetricStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD6dedb2cEncodeGithubComKubewardenK8sObjectsApiAutoscalingV2beta2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PodsMetricStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD6dedb2cDecodeGithubComKubewardenK8sObjectsApiAutoscalingV2beta2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PodsMetricStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD6dedb2cDecodeGithubComKubewardenK8sObjectsApiAutoscalingV2beta2(l, v)
}
