// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	_v1 "github.com/kubewarden/k8s-objects/apimachinery/pkg/apis/meta/v1"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE37f3cf0DecodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha1(in *jlexer.Lexer, out *ClusterTrustBundle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "apiVersion":
			out.APIVersion = string(in.String())
		case "kind":
			out.Kind = string(in.String())
		case "metadata":
			if in.IsNull() {
				in.Skip()
				out.Metadata = nil
			} else {
				if out.Metadata == nil {
					out.Metadata = new(_v1.ObjectMeta)
				}
				(*out.Metadata).UnmarshalEasyJSON(in)
			}
		case "spec":
			if in.IsNull() {
				in.Skip()
				out.Spec = nil
			} else {
				if out.Spec == nil {
					out.Spec = new(ClusterTrustBundleSpec)
				}
				easyjsonE37f3cf0DecodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha11(in, out.Spec)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE37f3cf0EncodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha1(out *jwriter.Writer, in ClusterTrustBundle) {
	out.RawByte('{')
	first := true
	_ = first
	if in.APIVersion != "" {
		const prefix string = ",\"apiVersion\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.APIVersion))
	}
	if in.Kind != "" {
		const prefix string = ",\"kind\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Kind))
	}
	if in.Metadata != nil {
		const prefix string = ",\"metadata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Metadata).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"spec\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Spec == nil {
			out.RawString("null")
		} else {
			easyjsonE37f3cf0EncodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha11(out, *in.Spec)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ClusterTrustBundle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE37f3cf0EncodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ClusterTrustBundle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE37f3cf0EncodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ClusterTrustBundle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE37f3cf0DecodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ClusterTrustBundle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE37f3cf0DecodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha1(l, v)
}
func easyjsonE37f3cf0DecodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha11(in *jlexer.Lexer, out *ClusterTrustBundleSpec) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "signerName":
			out.SignerName = string(in.String())
		case "trustBundle":
			if in.IsNull() {
				in.Skip()
				out.TrustBundle = nil
			} else {
				if out.TrustBundle == nil {
					out.TrustBundle = new(string)
				}
				*out.TrustBundle = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE37f3cf0EncodeGithubComKubewardenK8sObjectsApiCertificatesV1alpha11(out *jwriter.Writer, in ClusterTrustBundleSpec) {
	out.RawByte('{')
	first := true
	_ = first
	if in.SignerName != "" {
		const prefix string = ",\"signerName\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.SignerName))
	}
	{
		const prefix string = ",\"trustBundle\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.TrustBundle == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.TrustBundle))
		}
	}
	out.RawByte('}')
}
