// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC9eb25e1DecodeGithubComKubewardenK8sObjectsApiDiscoveryV1beta1(in *jlexer.Lexer, out *EndpointPort) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "appProtocol":
			out.AppProtocol = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "port":
			out.Port = int32(in.Int32())
		case "protocol":
			out.Protocol = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC9eb25e1EncodeGithubComKubewardenK8sObjectsApiDiscoveryV1beta1(out *jwriter.Writer, in EndpointPort) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AppProtocol != "" {
		const prefix string = ",\"appProtocol\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.AppProtocol))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Port != 0 {
		const prefix string = ",\"port\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Port))
	}
	if in.Protocol != "" {
		const prefix string = ",\"protocol\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Protocol))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EndpointPort) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC9eb25e1EncodeGithubComKubewardenK8sObjectsApiDiscoveryV1beta1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EndpointPort) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC9eb25e1EncodeGithubComKubewardenK8sObjectsApiDiscoveryV1beta1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EndpointPort) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC9eb25e1DecodeGithubComKubewardenK8sObjectsApiDiscoveryV1beta1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EndpointPort) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC9eb25e1DecodeGithubComKubewardenK8sObjectsApiDiscoveryV1beta1(l, v)
}
