// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1

import (
	json "encoding/json"
	_v1 "github.com/kubewarden/k8s-objects/apimachinery/pkg/apis/meta/v1"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1e94f1dcDecodeGithubComKubewardenK8sObjectsApiCoordinationV1(in *jlexer.Lexer, out *Lease) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "apiVersion":
			out.APIVersion = string(in.String())
		case "kind":
			out.Kind = string(in.String())
		case "metadata":
			if in.IsNull() {
				in.Skip()
				out.Metadata = nil
			} else {
				if out.Metadata == nil {
					out.Metadata = new(_v1.ObjectMeta)
				}
				(*out.Metadata).UnmarshalEasyJSON(in)
			}
		case "spec":
			if in.IsNull() {
				in.Skip()
				out.Spec = nil
			} else {
				if out.Spec == nil {
					out.Spec = new(LeaseSpec)
				}
				easyjson1e94f1dcDecodeGithubComKubewardenK8sObjectsApiCoordinationV11(in, out.Spec)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1e94f1dcEncodeGithubComKubewardenK8sObjectsApiCoordinationV1(out *jwriter.Writer, in Lease) {
	out.RawByte('{')
	first := true
	_ = first
	if in.APIVersion != "" {
		const prefix string = ",\"apiVersion\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.APIVersion))
	}
	if in.Kind != "" {
		const prefix string = ",\"kind\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Kind))
	}
	if in.Metadata != nil {
		const prefix string = ",\"metadata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Metadata).MarshalEasyJSON(out)
	}
	if in.Spec != nil {
		const prefix string = ",\"spec\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson1e94f1dcEncodeGithubComKubewardenK8sObjectsApiCoordinationV11(out, *in.Spec)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Lease) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1e94f1dcEncodeGithubComKubewardenK8sObjectsApiCoordinationV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Lease) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1e94f1dcEncodeGithubComKubewardenK8sObjectsApiCoordinationV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Lease) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1e94f1dcDecodeGithubComKubewardenK8sObjectsApiCoordinationV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Lease) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1e94f1dcDecodeGithubComKubewardenK8sObjectsApiCoordinationV1(l, v)
}
func easyjson1e94f1dcDecodeGithubComKubewardenK8sObjectsApiCoordinationV11(in *jlexer.Lexer, out *LeaseSpec) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "acquireTime":
			if in.IsNull() {
				in.Skip()
				out.AcquireTime = nil
			} else {
				if out.AcquireTime == nil {
					out.AcquireTime = new(_v1.MicroTime)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.AcquireTime).UnmarshalJSON(data))
				}
			}
		case "holderIdentity":
			out.HolderIdentity = string(in.String())
		case "leaseDurationSeconds":
			out.LeaseDurationSeconds = int32(in.Int32())
		case "leaseTransitions":
			out.LeaseTransitions = int32(in.Int32())
		case "renewTime":
			if in.IsNull() {
				in.Skip()
				out.RenewTime = nil
			} else {
				if out.RenewTime == nil {
					out.RenewTime = new(_v1.MicroTime)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.RenewTime).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1e94f1dcEncodeGithubComKubewardenK8sObjectsApiCoordinationV11(out *jwriter.Writer, in LeaseSpec) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AcquireTime != nil {
		const prefix string = ",\"acquireTime\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((*in.AcquireTime).MarshalJSON())
	}
	if in.HolderIdentity != "" {
		const prefix string = ",\"holderIdentity\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.HolderIdentity))
	}
	if in.LeaseDurationSeconds != 0 {
		const prefix string = ",\"leaseDurationSeconds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.LeaseDurationSeconds))
	}
	if in.LeaseTransitions != 0 {
		const prefix string = ",\"leaseTransitions\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.LeaseTransitions))
	}
	if in.RenewTime != nil {
		const prefix string = ",\"renewTime\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((*in.RenewTime).MarshalJSON())
	}
	out.RawByte('}')
}
